version: "3.3"

services:
  nginx:
    image: nginx:1.23.0-alpine
    container_name: 'nginx-service'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx.conf:/config.conf
      - ./config:/config
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    restart: always
  app:
    image: tolgee/tolgee
    volumes:
      - ./../tolgee/data:/data
      - ./../tolgee/config.yaml:/config.yaml
    ports:
      - '25432:25432'
      - '8000:8000'
    environment:
      spring.config.additional-location: file:///config.yaml
